version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
    # Labels on pull requests for security and version updates
    target-branch: "develop"
    labels:
      - "npm dependencies"
      
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
    # Labels on pull requests for security and version updates
    target-branch: "feature*"
    labels:
      - "npm dependencies"
