version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
    # Labels on pull requests for security and version updates
    target-branch: "Test"
    labels:
      - "npm dependencies"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
      
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
    # Labels on pull requests for security and version updates
    target-branch: "main"
    labels:
      - "npm dependencies"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    
  - package-ecosystem: "pip"
    directory: "authn-service/"
    schedule:
      interval: "daily"
    # Labels on pull requests for security and version updates
    target-branch: "Test"
    labels:
      - "pip dependencies"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 10
      
 

